### ISSUE TITLE
Interval timer for sitting/ standing/ looking away from screens, or whatever the user wants it for

### ISSUE THREAD

**Issue by aklambert** [aklambert/Wellness-Journal#11]
## Epic Purpose/ User Story Description:
Users who work at a desk a lot, and who are interested in keeping healthy, will be interested in an interval timer that they can use to remind them to switch between sitting and standing. 

This will be on a `Timer` page

## User Requirements:
Requirement 3.

## System Requirements:
- [x] The system will have a timer screen, which is a screen dedicated to the timer function
- [x] The timer screen will have a timer function, which will set an alarm after the time in hours and/or minutes that the user inputs has passed
- [x] The input for minutes and input for hours are integer values
- [x] The default value for all fields of seconds, minutes and hours is 0
- [x] Users may enter minutes and not hours, hours and not minutes, both minutes and hours, or not enter any of these values
- [x] A timer will be set, after saving valid inputs for hours and minutes 
- [x] Once the set time has passed, an alarm will go off on the mobile device.
- [x] There will be a way to cancel the timer
- [x] The timer will keep running when the user closes the application

## Any notes, images, flows or resources that may be helpful:
![Timer function flow](https://github.com/aklambert/Wellness-Journal/assets/57999183/2462b631-dfd1-4bbc-a35d-69a552213327)
