### ISSUE TITLE
Click into a workout from where workouts are listed, leading to a workout progression feature

### ISSUE THREAD

**Issue by aklambert** [aklambert/Wellness-Journal#8]
## Epic Purpose/ User Story Description:
Users using the custom workout and exercise features will want to be able to track what exercises they have completed in their custom workout so that they can monitor their exercise completion progress.

## User Requirements:
(see above)
## System Requirements:
- [x] #54
   - [x] save the workout log id
   - [x] save the workout id
   - [x] save the workout log date
- [x] #55
- [x] #58
- [x] #57

## Any notes, images, flows or resources that may be helpful:
